news_blog/news/urls.py
from django.urls import path
from .views import NewsView, NewsDetail, AddComment, LikeView, AddNewsView, SearchView, FilterCategoryNewsView, \
    MainFilterNewsView, NewsEditView


urlpatterns = [
    path('', NewsView.as_view(), name='news_list'),
    path('search/', SearchView.as_view(), name='search'),
    path('filter/<str:slug>/', MainFilterNewsView.as_view(), name='filter'),
    path('filter_category/', FilterCategoryNewsView.as_view(), name='filter_category'),
    path('<int:pk>/', NewsDetail.as_view(), name='news_detail'),
    path('<int:pk>/edit/', NewsEditView.as_view(), name='news_edit'),
    path('review/<int:pk>/', AddComment.as_view(), name='add_comment'),
    path('like/', LikeView.as_view(), name='add_like'),
    path('add_news/', AddNewsView.as_view(), name='add_news'),
]

news_blog/news_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('adminmanb/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),
    path('dialogs/', include('dialogs.urls')),
    path('pages/', include('custom_flatpages.urls')),
    path('contact_us/', include('contact_us.urls')),
    path('', include('news.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'custom_error.views.error_400'
handler401 = 'custom_error.views.error_401'
handler403 = 'custom_error.views.error_403'
handler404 = 'custom_error.views.error_404'
handler500 = 'custom_error.views.error_500'
handler502 = 'custom_error.views.error_502'
handler503 = 'custom_error.views.error_503'

news_blog/profiles/urls.py
from django.urls import path
from .views import ProfileView, ProfileEditView, AddFavouriteView, FavouriteListView, ProfileNewsView, \
    ProfileCommentsView, ProfilePublicInfo, PublicProfileNewsView, PublicProfileCommentsView, FollowProfileView, \
    ProfileFavoritesView, ProfileFollowView, ProfileSubscribersView, ProfileSubscriptionsView, PublicProfileFollowView, \
    PublicProfileSubscriptionsView, PublicProfileSubscribersView, PublicProfileFavoritesView

urlpatterns = [
    path('', ProfileView.as_view(), name='view_profile'),
    path('edit_profile/', ProfileEditView.as_view(), name='edit_profile'),
    path('public-info/<int:pk>/', ProfilePublicInfo.as_view(), name='public_info'),
    path('add_favorite/', AddFavouriteView.as_view(), name='add_favorite'),
    path('add_follow/', FollowProfileView.as_view(), name='add_follow'),
    path('favorites2/', FavouriteListView.as_view(), name='favorites'),

    path('news/', ProfileNewsView.as_view(), name='profile_news'),
    path('comments/', ProfileCommentsView.as_view(), name='profile_comments'),
    path('follow/', ProfileFollowView.as_view(), name='profile_follow'),
    path('subscribers/', ProfileSubscribersView.as_view(), name='profile_subscribers'),
    path('subscriptions/', ProfileSubscriptionsView.as_view(), name='profile_subscriptions'),
    path('favorites/', ProfileFavoritesView.as_view(), name='profile_favorites'),

    path('public-info/<int:pk>/news/', PublicProfileNewsView.as_view(), name='public_profile_news'),
    path('public-info/<int:pk>/comments/', PublicProfileCommentsView.as_view(), name='public_profile_comments'),
    path('public-info/<int:pk>/follow/', PublicProfileFollowView.as_view(), name='public_profile_follow'),
    path('public-info/<int:pk>/subscribers/', PublicProfileSubscribersView.as_view(),
         name='public_profile_subscribers'),
    path('public-info/<int:pk>/subscriptions/', PublicProfileSubscriptionsView.as_view(),
         name='public_profile_subscriptions'),
    path('public-info/<int:pk>/favorites/', PublicProfileFavoritesView.as_view(), name='public_profile_favorites'),
]

news_blog/profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from profiles.services import get_path_upload_avatar


class Profile(models.Model):
    """Модель профиля пользователя"""
    user = models.OneToOneField(User, verbose_name='Пользователь', on_delete=models.CASCADE, related_name='profile',
                                primary_key=True)
    nickname = models.CharField('Псевдоним', max_length=20, null=True, blank=True)
    avatar = models.ImageField('Аватар', upload_to=get_path_upload_avatar, null=True, blank=True)

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def __str__(self):
        return f'{self.user}'

    def get_all_like(self):
        news = self.user.news.all()
        comments = self.user.comment.all()
        all_like = 0
        for i in news:
            all_like += i.like
        for comment in comments:
            all_like += comment.like
        return all_like

    @property
    def get_avatar_url(self):
        if self.avatar:
            return '/media/{}'.format(self.avatar)
        else:
            return '/static/img/default.png'


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    """Создание профиля пользователя при регистрации"""
    if created:
        Profile.objects.create(user=instance, pk=instance.pk)
        instance.profile.save()


class UserFollowing(models.Model):
    user_id = models.ForeignKey(User, verbose_name='Подписки', related_name="following", on_delete=models.CASCADE)
    following_user_id = models.ForeignKey(User, verbose_name='Подписчики', related_name="followers",
                                          on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписчики'
        unique_together = ('user_id', 'following_user_id')

news_blog/profiles/forms.py
from django import forms
from .models import Profile
from .validators import avatar_validation, nickname_validation


class ProfileForm(forms.ModelForm):
    """Форма для редактирования данных профиля"""

    class Meta:
        model = Profile
        fields = ['nickname', 'avatar']
        widgets = {
            'nickname': forms.TextInput(attrs={'class': 'form-edit-profile__input', 'placeholder': "Заголовок..."}),
            'avatar': forms.ClearableFileInput(attrs={'class': ''}),
        }

    def clean_avatar(self):
        avatar = self.cleaned_data['avatar']
        if avatar:
            avatar_validation(avatar=avatar)
            return avatar

    def clean_nickname(self):
        nickname = self.cleaned_data['nickname']
        if nickname:
            nickname_validation(nickname=nickname)
            return nickname

news_blog/profiles/views.py
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.base import View
from news.models import News
from .models import Profile, UserFollowing
from .forms import ProfileForm
from django.views.generic import UpdateView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages


class ProfileView(LoginRequiredMixin, DetailView):
    """Вывод профиля пользователя"""
    model = Profile
    context_object_name = 'profile'
    template_name = 'profiles/profile_detail.html'

    def get_object(self, queryset=None):
        obj = get_object_or_404(Profile, user=self.request.user)
        if obj.user != self.request.user:
            raise Http404
        return obj


class ProfileEditView(LoginRequiredMixin, UpdateView):
    """Редактирование профиля"""
    form_class = ProfileForm
    model = Profile
    template_name = 'profiles/profile_edit.html'
    success_url = reverse_lazy('edit_profile')

    def get_object(self, queryset=None):
        return self.request.user.profile

    def form_valid(self, form):
        messages.success(self.request, 'Profile has been updated!')
        return super().form_valid(form)


class ProfilePublicInfo(LoginRequiredMixin, DetailView):
    """Публичный профиль пользователя"""
    model = Profile
    context_object_name = 'profile'
    template_name = 'profiles/public_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Проверяем подписан ли пользователь на данный профиль
        context['follow'] = UserFollowing.objects.filter(user_id=self.get_object().user,
                                                         following_user_id=self.request.user).exists()
        return context

    def dispatch(self, request, *args, **kwargs):
        # Если публичный профиль ведёт на нас, перенаправляем на личный профиль
        pk = self.kwargs.get('pk')
        if self.request.user.profile.pk == pk:
            return redirect('view_profile')
        self.get_object()
        return super(ProfilePublicInfo, self).get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        pk = self.kwargs.get('pk')
        obj = get_object_or_404(Profile, pk=pk)
        return obj


class AddFavouriteView(LoginRequiredMixin, View):
    """Добавить в закладки"""

    def get(self, request):
        raise Http404

    def post(self, request):
        pk = request.POST.get("pk")
        news = News.objects.get(pk=pk)
        if news.favourites.filter(id=request.user.id).exists():
            news.favourites.remove(request.user)
            counter = news.favourites.count()
            result = False
        else:
            news.favourites.add(request.user)
            counter = news.favourites.count()
            result = True
        news.save()
        return JsonResponse({'result': result, 'counter': counter, })


class FavouriteListView(LoginRequiredMixin, ListView):
    """Список новостей в закладках"""
    model = News
    template_name = 'profiles/profile_favourites_sidebar.html'
    context_object_name = 'favorites_list'
    paginate_by = 5

    def get_queryset(self):
        queryset = News.objects.filter(favourites=self.request.user)
        return queryset


class FollowProfileView(LoginRequiredMixin, View):
    """Подписаться на профиль"""

    def post(self, request):
        pk = request.POST.get("pk")
        profile = Profile.objects.get(pk=pk)
        follow = UserFollowing.objects.filter(user_id=profile.user, following_user_id=self.request.user).exists()
        if follow:
            UserFollowing.objects.filter(user_id=profile.user, following_user_id=self.request.user).delete()
            result = False
        else:
            UserFollowing.objects.create(user_id=profile.user, following_user_id=self.request.user)
            result = True
        return JsonResponse({'result': result})


class ProfileNewsView(LoginRequiredMixin, ListView):
    """В профиле пользователя написанные им статьи"""
    model = Profile
    template_name = 'profiles/profile_news.html'
    context_object_name = 'profile_news'
    paginate_by = 5

    def get_profile(self):
        profile = get_object_or_404(Profile, user=self.request.user)
        return profile

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        profile = self.get_profile()
        context['profile'] = profile
        return context

    def get_queryset(self):
        profile = self.get_profile()
        queryset = profile.user.news.all()
        return queryset


class ProfileCommentsView(ProfileNewsView):
    """В профиле пользователя написанные им комментарии"""
    model = Profile
    template_name = 'profiles/profile_comments.html'
    context_object_name = 'profile_comments'
    paginate_by = 5

    def get_queryset(self):
        profile = self.get_profile()
        queryset = profile.user.comment.all()
        return queryset


class ProfileFavoritesView(ProfileNewsView):
    """В профиле пользователя его закладки"""
    model = Profile
    template_name = 'profiles/profile_favorites.html'
    context_object_name = 'profile_favorites'
    paginate_by = 5

    def get_queryset(self):
        profile = self.get_profile()
        queryset = News.objects.filter(favourites=profile.user)
        return queryset


class ProfileFollowView(ProfileNewsView):
    """В профиле пользователя подписки и подписчики"""
    model = Profile
    template_name = 'profiles/profile_follow.html'
    context_object_name = 'profile_follow'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        # Выводим информацию о пользователи
        profile = self.get_profile()

        # Списки подписок и подписчиков
        context['following_list'] = self.get_following(profile)[:6]
        context['followers_list'] = self.get_followers(profile)[:6]

        return context

    def get_following(self, profile):
        # Списки подписок
        following_list = UserFollowing.objects.filter(following_user_id=profile.user)
        return following_list

    def get_followers(self, profile):
        # Списки подписчиков
        followers_list = UserFollowing.objects.filter(user_id=profile.user)
        return followers_list


class ProfileSubscriptionsView(ProfileFollowView):
    """В профиле пользователя выводим все подписки"""
    model = Profile
    template_name = 'profiles/profile_subscriptions.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        # Выводим информацию о пользователи
        profile = self.get_profile()

        # Передаём список подписок
        context['following_list'] = self.get_following(profile)
        return context


class ProfileSubscribersView(ProfileFollowView):
    """В профиле пользователя выводим всх подписчиков"""
    model = Profile
    template_name = 'profiles/profile_subscribers.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        # Выводим информацию о пользователи
        profile = self.get_profile()

        # Передаём список подписчиков
        context['followers_list'] = self.get_followers(profile)

        # Передаём список подписок пользователя для сравнения
        context['subscriptions_list'] = self.get_user_subscriptions(profile)
        return context

    def get_user_subscriptions(self, profile):
        # Список подписок для сравнения
        following_list = []
        for i in UserFollowing.objects.filter(following_user_id=profile.user):
            following_list.append(i.user_id)
        return following_list


class PublicProfileNewsView(ProfileNewsView):
    """В публичном профиле пользователя написанные им статьи"""
    model = Profile
    template_name = 'profiles/public_profile_news.html'
    context_object_name = 'profile_news'
    paginate_by = 5

    def get_public_profile(self):
        # Выводим публичную информацию о пользователи
        pk = self.kwargs.get('pk')
        profile = get_object_or_404(Profile, pk=pk)
        return profile

    def check_follow(self, public_profile, profile):
        # Проверяем подписан ли пользователь на данный профиль
        follow = UserFollowing.objects.filter(user_id=public_profile.user,
                                              following_user_id=profile.user).exists()
        return follow

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        # Выводим публичную информацию о пользователи
        profile = self.get_profile()
        public_profile = self.get_public_profile()
        context['profile'] = public_profile
        context['follow'] = self.check_follow(public_profile=public_profile, profile=profile)
        return context

    def get_queryset(self):
        # Статьи пользователя
        profile = self.get_public_profile()
        queryset = profile.user.news.all()
        return queryset


class PublicProfileCommentsView(PublicProfileNewsView):
    """В публичном профиле пользователя написанные им комментарии"""
    model = Profile
    template_name = 'profiles/public_profile_comments.html'
    context_object_name = 'profile_comments'
    paginate_by = 5

    def get_queryset(self):
        # Комментарии пользователя
        profile = self.get_public_profile()
        queryset = profile.user.comment.all()
        return queryset


class PublicProfileFavoritesView(PublicProfileNewsView):
    """В публичном профиле пользователя написанные им комментарии"""
    model = Profile
    template_name = 'profiles/public_profile_favorites.html'
    context_object_name = 'profile_favorites'
    paginate_by = 5

    def get_queryset(self):
        # Закладки пользователя

news_blog/templates/profiles/profile_comments.html
{% extends 'profiles/profile_detail.html' %}
{% block profile_content %}
{% load static profiles_tag %}
    <div class="profile__comments comments">
        <ul class="comments__list">

            {% for comment in profile_comments %}
                <li class="comments__item comment">
                    <div class="comment__info">
                        
                        {% if comment.author.profile.avatar %}
                            {% get_webp_avatar comment.author.profile.user.id as webp_img %}
                            <picture>
                                {% if webp_img %}
                                    <source srcset="{% static webp_img %}" type="image/webp">
                                {% endif %}
                                <img src="{{ comment.author.profile.get_avatar_url }}" alt="{{ comment.author }}" class="comment__avatar">
                            </picture>
                        {% else %}
                            <img src="{{ comment.author.profile.get_avatar_url }}" alt="{{ comment.author }}" class="comment__avatar">
                        {% endif %}

                        <div class="comment__user-info">
                            <div class="comment__username">
                                <a class="comment__username-link" href="#">
                                    {{ comment.author }}
                                </a>
                            </div>
                            <div class="comment__datetime">
                                {{ comment.created_at }}
                            </div>
                        </div>
                    </div>
                    <p class="comment__text">
                         {{ comment.text }}
                    </p>

                    <!-- Comment action -->
                    <div class="comments__action">
                        <div class="comment__action-right">
                            <button class="news-actions__btn {% if user in  node.user_like.all %} _active {% endif %}" aria-hidden="true" onclick="like({{ comment.pk }}, 'comment')" id="comment_like_btn{{ comment.pk }}">
                                <svg class="news-actions__icon _like"  xmlns="http://www.w3.org/2000/svg" viewbox="0 0 14 14">
                                    <path d="M9.727273 2.090909c-1.1454548 0-2.1545457.572727-2.727273 1.472727-.5727273-.9-1.5818182-1.472727-2.7272727-1.472727C2.4727273 2.090909 1 3.563636 1 5.363636c0 3.245455 6 6.545455 6 6.545455s6-3.272727 6-6.545455c0-1.8-1.472727-3.272727-3.272727-3.272727z"/>
                                </svg>
                            </button>
                            <span id="comment_counter__likes{{ comment.pk }}">
                                {{ comment.like }}
                            </span>
                        </div>
                    </div>
                </li>
            {% empty %}
                <li class="comments__item">
                    <p class="not_found">
                        Ничего не найдено...
                    </p>
                </li>
            {% endfor %}
        </ul>
        <!--Pages-->
        <div class="pages">
            {% include 'include/pagination.html' %}
        </div>
    </div>

{% endblock profile_content %}

news_blog/templates/profiles/profile_edit.html
{% extends 'news/base.html' %}
{% block title %} Edit profile {% endblock title %}
{% load static %}
{% block main_content %}
    <section class="profile-edit">
        <div class="profile-edit__container">
            <div class="profile-edit__row">

                <!-- Edit banner -->
                <div class="profile-edit__banner banner">
                    <span class="banner__img"></span>
                </div>
                
                <div class="profile-edit__info">
                    {% comment %}
                        {% if messages %}
                            {% for message in messages %}
                            {{ message }}
                            <!-- Messages alert -->
                                <div class="profile-edit__messages" role="alert">
                                    <button class="btn btn_alert" data-dismiss="alert">
                                        {{message}}
                                        <small><sup>x</sup></small>
                                    </button>
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endcomment %}

                    <!-- Edit form -->
                    <form class="profile-edit__form-edit-profile form-edit-profile" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        <label for="id_nickname" class="form-edit-profile__heading title">
                            Псевдоним
                        </label>
                        <div class="form-edit-profile__error">
                            {{ form.errors.nickname }}
                        </div>
                        {{ form.nickname }}

                        <label for="profile_avatar" class="form-edit-profile__heading title">
                            Загрузить аватар
                        </label>
                        <div class="form-edit-profile__error">
                            {{ form.errors.avatar }}
                        </div>
                        <div class="form-edit-profile__image-upload image-upload" id="profile_avatar">
                            <div id="file_name" class="image-upload__file-name _right"></div>
                            <button type="button" class="image-upload__btn btn _right" onclick="uploadAvatar()">
                                <svg class="image-upload__btn-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                    <path d="M4 6H2v14c0 1.1.9 2 2 2h14v-2H4V6zm16-4H8c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-1 9h-4v4h-2v-4H9V9h4V5h2v4h4v2z"/>
                                </svg>
                                Аватар
                            </button>
                        </div>
                        <div class="form-edit-profile__hide">
                            {{ form.avatar }}
                        </div>
                        <button type="submit" class="form-edit-profile__submit btn-border">
                            Сохранить
                        </button>
                    </form>
                </div>
            </div>
        </div>
        
        <!-- Back to profile -->
        <a href="{% url 'view_profile' %}" class="profile-edit__close close">
            <svg class="close__icon" enable-background="new 0 0 128 128" height="128px" id="Layer_1" version="1.1" viewbox="0 0 128 128" width="128px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <path d="M81.646,64l22.248-22.249c3.48-3.48,3.474-9.131-0.019-12.623l-5.006-5.005  c-3.489-3.49-9.142-3.499-12.622-0.019L64,46.354L41.753,24.106c-3.484-3.483-9.133-3.472-12.624,0.018l-5.005,5.005  c-3.491,3.492-3.501,9.14-0.018,12.623L46.354,64L24.108,86.246c-3.483,3.484-3.472,9.133,0.018,12.623l5.005,5.006  c3.492,3.492,9.14,3.502,12.623,0.018L64,81.647l22.247,22.246c3.48,3.481,9.131,3.475,12.622-0.019l5.006-5.006  c3.489-3.489,3.498-9.142,0.019-12.622L81.646,64z"/>
            </svg>
        </a>
    </section>
{% endblock main_content %}

news_blog/templates/profiles/profile_favorites.html
{% extends 'profiles/profile_detail.html' %}
{% block profile_content %}
{% load static news_tag %}
    <div class="profile__favorites news">

        <ul class="news__list">
            {% for news in profile_favorites %}
                <li class="news__item">
                    <a class="news__link"></a>

                    {% if news.image %}
                        <a class="news__img-link" href="/{{ news.pk }}">

                            {% get_webp_img news.pk as webp_img %}
                            <picture class="news__img-container">
                                {% if webp_img %}
                                    <source srcset="{% static webp_img.webp_x2 %} 2x, {% static webp_img.webp_x1 %} 1x" type="image/webp">
                                {% endif %}
                                <img src="{{ news.image.url }}" alt="image" class="news__img">
                            </picture>

                        </a>
                    {% endif %}

                    <div class="news__news-info news__info">
                        <h2 class="news-info__title title_black">
                            <a class="news-info__link" href="/{{ news.pk }}">
                                {{ news.title }}
                            </a>
                        </h2>

                        <!-- News actions -->
                        <div class="news__action news-actions">
                            <ul class="news-actions__list">
                                <li class="news-actions__item">
                                    <a class="news-actions__btn" href="#">
                                        <span class="news-actions__icon _views"></span>
                                    </a>
                                    {{ news.views }}
                                </li>
                                <li class="news-actions__item">
                                    <a class="news-actions__btn" href="/{{ news.pk }}">
                                        <span class="news-actions__icon _comments"></span>
                                    </a>
                                    {{ news.get_comment.count }}
                                </li>

                                {% if user.is_authenticated %}
                                    <li class="news-actions__item">
                                        <button class="news-actions__btn {% if user in  news.user_like.all %} _active {% endif %}" aria-hidden="true" onclick="like({{ news.pk }}, 'news')" id="like_btn{{ news.pk }}">
                                            <svg class="news-actions__icon _like" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 14 14">
                                                <path d="M9.727273 2.090909c-1.1454548 0-2.1545457.572727-2.727273 1.472727-.5727273-.9-1.5818182-1.472727-2.7272727-1.472727C2.4727273 2.090909 1 3.563636 1 5.363636c0 3.245455 6 6.545455 6 6.545455s6-3.272727 6-6.545455c0-1.8-1.472727-3.272727-3.272727-3.272727z"/>
                                            </svg>
                                        </button>
                                        <span id="counter__likes{{ news.pk }}">
                                            {{ news.like }}
                                        </span>
                                    </li>
                                    <li class="news-actions__item">
                                        <a class="news-actions__btn {% if user in  news.favourites.all %} _active {% endif %}" aria-hidden="true" onclick="favorite({{ news.pk }})" id="favorite_btn{{ news.pk }}">
                                            <svg class="news-actions__icon _favorite" version="1.1" x="0px" y="0px" viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
                                                <path d="M839.4,10c9.9,0,19.4,1.9,28.5,5.8c14.3,5.6,25.6,14.5,34,26.6c8.4,12.1,12.6,25.5,12.6,40.2v834.9c0,14.7-4.2,28.1-12.6,40.2c-8.4,12.1-19.8,20.9-34,26.6c-8.2,3.5-17.7,5.2-28.5,5.2c-20.7,0-38.6-6.9-53.8-20.7L500,694L214.4,968.6c-15.5,14.3-33.5,21.4-53.8,21.4c-9.9,0-19.4-1.9-28.5-5.8c-14.3-5.6-25.6-14.5-34-26.6c-8.4-12.1-12.6-25.5-12.6-40.2V82.5c0-14.7,4.2-28.1,12.6-40.2c8.4-12.1,19.8-20.9,34-26.6c9.1-3.9,18.6-5.8,28.5-5.8H839.4L839.4,10z"/>
                                            </svg>
                                        </a>
                                        <span id="counter__favorite{{ news.pk }}">
                                            {{ news.favourites.count }}
                                        </span>
                                    </li>
                                {% else %}
                                    <li class="news-actions__item">
                                        <a href="#login" class="news-actions__btn popup-link">
                                            <svg class="news-actions__icon _like" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 14 14">
                                                <path d="M9.727273 2.090909c-1.1454548 0-2.1545457.572727-2.727273 1.472727-.5727273-.9-1.5818182-1.472727-2.7272727-1.472727C2.4727273 2.090909 1 3.563636 1 5.363636c0 3.245455 6 6.545455 6 6.545455s6-3.272727 6-6.545455c0-1.8-1.472727-3.272727-3.272727-3.272727z"/>
                                            </svg>
                                        </a>
                                        {{ news.like }}
                                    </li>
                                    <li class="news-actions__item">
                                        <a href="#login" class="news-actions__btn popup-link">
                                            <svg class="news-actions__icon _favorite" version="1.1" x="0px" y="0px" viewBox="0 0 1000 1000" enable-background="new 0 0 1000 1000" xml:space="preserve">
                                                <path d="M839.4,10c9.9,0,19.4,1.9,28.5,5.8c14.3,5.6,25.6,14.5,34,26.6c8.4,12.1,12.6,25.5,12.6,40.2v834.9c0,14.7-4.2,28.1-12.6,40.2c-8.4,12.1-19.8,20.9-34,26.6c-8.2,3.5-17.7,5.2-28.5,5.2c-20.7,0-38.6-6.9-53.8-20.7L500,694L214.4,968.6c-15.5,14.3-33.5,21.4-53.8,21.4c-9.9,0-19.4-1.9-28.5-5.8c-14.3-5.6-25.6-14.5-34-26.6c-8.4-12.1-12.6-25.5-12.6-40.2V82.5c0-14.7,4.2-28.1,12.6-40.2c8.4-12.1,19.8-20.9,34-26.6c9.1-3.9,18.6-5.8,28.5-5.8H839.4L839.4,10z"/>
                                            </svg>
                                        </a>
                                        {{ news.favourites.count }}
                                    </li>
                                {% endif %}
                            </ul>

                        </div>
                    </div>
                </li>
            {% empty %}
                <li class="news__item">
                    <div class="news__news-info">
                        <p class="not_found">
                            Ничего не найдено...
                        </p>
                    </div>
                </li>
            {% endfor %}
        </ul>

        {% if paginator.page_range|length > 1 %}
            <div class="pages">
                {% include 'include/pagination.html' %}
            </div>
        {% endif %}
    </div>
{% endblock profile_content %}