news_blog/news/urls.py
from django.urls import path
from .views import NewsView, NewsDetail, AddComment, LikeView, AddNewsView, SearchView, FilterCategoryNewsView, \
    MainFilterNewsView, NewsEditView


urlpatterns = [
    path('', NewsView.as_view(), name='news_list'),
    path('search/', SearchView.as_view(), name='search'),
    path('filter/<str:slug>/', MainFilterNewsView.as_view(), name='filter'),
    path('filter_category/', FilterCategoryNewsView.as_view(), name='filter_category'),
    path('<int:pk>/', NewsDetail.as_view(), name='news_detail'),
    path('<int:pk>/edit/', NewsEditView.as_view(), name='news_edit'),
    path('review/<int:pk>/', AddComment.as_view(), name='add_comment'),
    path('like/', LikeView.as_view(), name='add_like'),
    path('add_news/', AddNewsView.as_view(), name='add_news'),
]

news_blog/news_blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('adminmanb/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('profiles/', include('profiles.urls')),
    path('dialogs/', include('dialogs.urls')),
    path('pages/', include('custom_flatpages.urls')),
    path('contact_us/', include('contact_us.urls')),
    path('', include('news.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'custom_error.views.error_400'
handler401 = 'custom_error.views.error_401'
handler403 = 'custom_error.views.error_403'
handler404 = 'custom_error.views.error_404'
handler500 = 'custom_error.views.error_500'
handler502 = 'custom_error.views.error_502'
handler503 = 'custom_error.views.error_503'

news_blog/news/models.py
from django.db import models
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey
from ckeditor.fields import RichTextField
from .service import get_path_upload_news_image


class Category(models.Model):
    name = models.CharField('Название', max_length=100)
    description = models.TextField('Описание')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class News(models.Model):
    """Новость"""
    title = models.CharField('Заголовок', max_length=150)
    description = RichTextField('Описание', blank=True, null=True)
    created_at = models.DateTimeField('Время публикации', auto_now_add=True)
    updated_at = models.DateTimeField('Время обновления публикации', auto_now=True)
    image = models.ImageField('Постер', upload_to=get_path_upload_news_image, blank=True, null=True)
    author = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, related_name="news")
    like = models.IntegerField('Like', default=0)
    user_like = models.ManyToManyField(User, verbose_name="Кто поставил like", related_name="users_like_news")
    views = models.IntegerField('Views', default=0)
    # url = models.SlugField(max_length=100, unique=True)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.PROTECT, default=None, null=True)
    favourites = models.ManyToManyField(User, related_name='favourite', default=None, blank=True)

    def __str__(self):
        return self.title

    def get_comment(self):
        return self.comment_set.all()

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['-created_at']


class Comment(MPTTModel):
    """Комментарий"""
    author = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE, related_name="comment")
    text = models.TextField('Сообщение', max_length=5000)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    news = models.ForeignKey(News, verbose_name='Новости', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    like = models.IntegerField(default=0, verbose_name='Like')
    user_like = models.ManyToManyField(User, verbose_name="Кто поставил like", related_name="users_like_comment")

    class MPTTMeta:
        order_insertion_by = ['-created_at']

    def __str__(self):
        return f'{self.author}'

news_blog/news/forms.py
from django import forms
from .models import Comment, News
from mptt.forms import TreeNodeChoiceField
from ckeditor.fields import RichTextFormField
from .validators import news_description_validation, news_image_validation, news_category_validation


class CommentForm(forms.ModelForm):
    """Форма для отправки комментария к новости"""
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'class': 'hide_all'})
        self.fields['parent'].label = ''
        self.fields['text'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        fields = ('parent', 'text',)
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-comment__textarea', 'placeholder': "Написать комментарий..."})
        }

    def save(self, *args, **kwargs):
        Comment.objects.rebuild()
        return super(CommentForm, self).save(*args, **kwargs)


class NewsForm(forms.ModelForm):
    """Форма для добавление новости"""

    class Meta:
        model = News
        fields = ('title', 'description', 'image', 'category')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-news__input', 'placeholder': "Заголовок..."}),
            'description': RichTextFormField(),
            'image': forms.ClearableFileInput(attrs={'class': ''}),
            'category': forms.Select(attrs={'class': 'select__select'}),
        }

    def clean_description(self):
        origin_description = self.cleaned_data['description']
        news_description_validation(origin_description)
        return origin_description

    def clean_image(self):
        image = self.cleaned_data['image']
        if image:
            news_image_validation(image=image)
            return image

    def clean_category(self):
        category = self.cleaned_data['category']
        news_category_validation(category=category)
        return category

news_blog/news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q, Count
from django.http import JsonResponse, Http404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.views.generic.base import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import News, Comment, Category
from .forms import CommentForm, NewsForm
from .service import send_news_id_to_image_path


class NewsView(ListView):
    """Список новостей"""
    model = News
    queryset = News.objects.all()
    context_object_name = 'news_list'
    paginate_by = 5


class NewsEditView(LoginRequiredMixin, UpdateView):
    model = News
    form_class = NewsForm
    template_name = 'news/news_edit.html'

    def get_context_data(self, **kwargs):
        content = super().get_context_data(**kwargs)
        content['categories'] = Category.objects.all()
        return content

    def dispatch(self, request, *args, **kwargs):
        if self.get_object().author != self.request.user:
            return redirect('/')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('news_detail', args=(self.get_object().pk,))


class NewsDetail(DetailView):
    """Список новостей"""
    model = News

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        context['all_comments'] = self.get_pages()
        context['views_counter'] = self.get_views()
        return context

    def get_views(self):
        """Добавляет просмотр к статье"""
        views_counter = self.object
        views_counter.views += 1
        views = views_counter.views
        views_counter.save()
        return views

    def get_pages(self):
        """Делит комментарии на страницы"""
        # TODO Доработать деление. Не выводить children элементы на следующую страницу
        all_comments = self.object.get_comment()
        page = self.request.GET.get('page', 1)
        paginator = Paginator(all_comments, 25)
        try:
            comments = paginator.page(page)
        except PageNotAnInteger:
            comments = paginator.page(1)
        except EmptyPage:
            comments = paginator.page(paginator.num_pages)
        return comments


class AddComment(LoginRequiredMixin, View):
    """Комментарии"""

    def get(self, request):
        raise Http404

    def post(self, request, pk):
        form = CommentForm(request.POST)
        news = News.objects.get(pk=pk)
        if form.is_valid():
            form = form.save(commit=False)
            if request.POST.get('parent', None):
                form.parent_id = int(request.POST.get('parent'))
            form.news = news
            form.author = request.user
            form.save()
        return redirect(f'/{pk}')


class LikeView(LoginRequiredMixin, View):
    """Поставить лайк"""

    def get(self, request):
        raise Http404

    def post(self, request):
        pk = request.POST.get("pk")
        model_name = request.POST.get("model")
        if model_name == 'news':
            news = News.objects.get(pk=pk)
            if request.user in news.user_like.all():
                news.user_like.remove(User.objects.get(pk=request.user.pk))
                news.like -= 1
                counter = news.like
                result = False
            else:
                news.user_like.add(User.objects.get(pk=request.user.pk))
                news.like += 1
                counter = news.like
                result = True
            news.save()
        else:
            comment = Comment.objects.get(pk=pk)
            if request.user in comment.user_like.all():
                comment.user_like.remove(User.objects.get(pk=request.user.pk))
                comment.like -= 1
                counter = comment.like
                result = False
            else:
                comment.user_like.add(User.objects.get(pk=request.user.pk))
                comment.like += 1
                counter = comment.like
                result = True
            comment.save()
        print(model_name)
        return JsonResponse({'result': result, 'counter': counter, 'model_name': model_name, })


class AddNewsView(LoginRequiredMixin, CreateView):
    model = News
    form_class = NewsForm
    template_name = 'news/add_news.html'

    def get_context_data(self, **kwargs):
        content = super().get_context_data(**kwargs)
        content['categories'] = Category.objects.all()
        return content

    def form_valid(self, form):
        form.instance.author = self.request.user

        if form.cleaned_data["image"]:
            send_news_id_to_image_path(form=form, request=self.request)

        form.save()
        return redirect('/')

    def get_success_url(self):
        return redirect('/')


class FilterCategoryNewsView(ListView):
    """Фильтр новостей по категории"""
    paginate_by = 5

    def get_queryset(self):
        queryset = News.objects.filter(
            category__in=self.request.GET.getlist('category')
        ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['category'] = ''.join([f'category={x}&'for x in self.request.GET.getlist('category')])
        return context


class SearchView(ListView):
    """Поиск новостей по заголовку и описанию"""
    paginate_by = 10

    def get_queryset(self):
        return News.objects.filter(
            Q(title__icontains=self.request.GET.get('q').capitalize()) |
            Q(description__icontains=self.request.GET.get('q').capitalize()),
        ).distinct()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['q'] = f"q={self.request.GET.get('q')}&"
        return context


class MainFilterNewsView(ListView):
    """Фильтр новостей по лайкам и комментариям"""
    paginate_by = 10

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        if slug == 'hot':
            # Сортировка статей по комментариям
            return News.objects.annotate(count=Count('comment')).order_by('-count').all()
        else:
            # Сортировка статей по лайкам
            return News.objects.order_by('-like').all()

news_blog/templates/news/add_news.html
{% extends 'news/base.html' %}
{% load static %}
{% block title %} Add News {% endblock title %}
{% block main_content %}
<section class="add-news">
    <form class="add-news__form-news form-news" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- title -->
        <div class="form-news__item">
            <label class="form-news__heading title" for="id_title">
                Заголовок статьи
            </label>
            <div class="form-news__error">
                {{ form.errors.title }}
            </div>
            {{ form.title }}
        </div>

        <!-- discription -->
        <div class="form-news__item">
            <label class="form-news__heading title" for="description_add">
                Текст статьи
            </label>
            <div class="form-news__error">
                {{ form.errors.description }}
            </div>
            <div class="form-news__description" id="description_add">
                {{ form.description | safe }}
                {{ form.media }}
            </div>
        </div>

        <!-- category -->
        <div class="form-news__item">
            <label class="form-news__heading title" for="category_add">
                Категория
            </label>
            <div class="form-news__error">
                {{ form.errors.category }}
            </div>
            <div class="form-news__select select" id="category_add">
                <button class="select__button" type="button">Аниме</button>
                <ul class="select__list">
                    {% for category in categories %}
                        <li class="select__item" data-value="{{ category.pk }}">
                            {{ category.name }}
                        </li>
                    {% endfor %}
                </ul>
                {{ form.category }}
            </div>
        </div>

        <!-- cover -->
        <div class="form-news__item">
            <label class="form-news__heading title" for="cover_add">
                Обложка
            </label>
            <div class="form-news__error">
                {{ form.errors.image }}
            </div>
            <div class="form-news__image-upload image-upload" id="cover_add">
                <div class="image-upload__file-name" id="file_name"></div>
                <button class="image-upload__btn btn" type="button" onclick="uploadImage()">
                    <svg class="image-upload__btn-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                        <path d="M4 6H2v14c0 1.1.9 2 2 2h14v-2H4V6zm16-4H8c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-1 9h-4v4h-2v-4H9V9h4V5h2v4h4v2z"/>
                    </svg>
                    Обложку
                </button>
            </div>
            <div class="form-news__hide">
                {{form.image}}
            </div>
        </div>
        <button class="form-news__submit btn _left" type="submit">
            Опубликовать
        </button>
    </form>
</section>
{% endblock main_content %}

news_blog/templates/news/base.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}
{% block content %}

{% include 'include/sidebar.html' %}

<section class="section-content">
    <div class="content__container">
        <div class="content__row">
            {% block main_content %}

            {% endblock main_content %}
        </div>
    </div>
</section>
{% include 'include/add.html' %}

{% endblock content %}

news_blog/templates/news/news_edit.html
{% extends 'news/base.html' %}
{% load static %}
{% block title %} Edit News {% endblock title %}
{% block main_content %}
    <section class="edit-news">
        <form class="edit-news__form-news form-news" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- title -->
            <div class="form-news__item">
                <label class="form-news__heading title" for="id_title">
                    Заголовок статьи
                </label>
                <div class="form-news__error">
                    {{ form.errors.title }}
                </div>
                {{ form.title }}
            </div>

            <!-- discription -->
            <div class="form-news__item">
                <label class="form-news__heading title" for="description_edit">
                    Текст статьи
                </label>
                <div class="form-news__error">
                    {{ form.errors.description }}
                </div>
                <div class="form-news__description" id="description_edit">
                    {{ form.description | safe }}
                    {{ form.media }}
                </div>
            </div>

            <!-- category -->
            <div class="form-news__item">
                <label class="form-news__heading title" for="category_edit">
                    Категория
                </label>
                <div class="form-news__error">
                    {{ form.errors.category }}
                </div>
                <div class="form-news__select select" id="category_edit">
                    <button class="select__button" type="button">Аниме</button>
                    <ul class="select__list">
                        {% for category in categories %}
                            <li class="select__item" data-value="{{ category.pk }}">
                                {{ category.name }}
                            </li>
                        {% endfor %}
                    </ul>
                    {{ form.category }}
                </div>
            </div>

            <!-- cover -->
            <div class="form-news__item">
                <label class="form-news__heading title" for="cover_edit">
                    Обложка
                </label>
                <div class="form-news__error">
                    {{ form.errors.image }}
                </div>
                <div class="form-news__image-upload image-upload" id="cover_edit">
                    <div class="image-upload__file-name" id="file_name"></div>
                    <button class="image-upload__btn btn" type="button" onclick="uploadImage()">
                        <svg class="image-upload__btn-icon" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <path d="M4 6H2v14c0 1.1.9 2 2 2h14v-2H4V6zm16-4H8c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-1 9h-4v4h-2v-4H9V9h4V5h2v4h4v2z"/>
                        </svg>
                        Обложка
                    </button>
                </div>
                <div class="form-news__hide">
                    {{form.image}}
                </div>
            </div>
            <button class="form-news__submit btn _left" type="submit">
                Сохранить
            </button>
        </form>
    </section>
{% endblock main_content %}